name: UnlimitedFirearms
main: com.unlimitedfirearms.core.BukkitCore
version: 0.0.1-SNAPSHOT
author: [berry64,LocyDragon]

commands:
  unlimitedfirearms:
    description: main command for UnlimitedFirearms
    aliases: [ufa, uf]